services:
  - type: web
    name: project-corpus
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python launcher.py
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: PORT
        value: 10000
    plan: free
